query GetRecentlyAxiesSold($from: Int, $size: Int) {
    settledAuctions {axies(from: $from, size: $size) {
        total
        results {...AxieSettledBrief transferHistory {...TransferHistoryInSettledAuction __typename} __typename } __typename }    __typename}}
fragment AxieSettledBrief on Axie {
    id
    name
    image
    class
    breedCount __typename}
fragment TransferHistoryInSettledAuction on TransferRecords {
    total
    results {...TransferRecordInSettledAuction    __typename} __typename}
fragment TransferRecordInSettledAuction on TransferRecord {
    from
    to
    timestamp
    withPrice
    withPriceUsd
    fromProfile {name __typename}
    toProfile {name __typename} __typename}
